# Setup
title: "Godot, Kotlin and Unity"
tagline: "On game design and coding"
description: 'gamedev gamedesign Unity Java Kotlin bijumon @bijupunalor bijumon.github.io hosted at <a href="https://help.github.com/articles/using-jekyll-with-pages/">github-pages</a>. modified <a href="https://github.com/poole/poole">poole</a> theme by <a href="http://markdotto.com/about/">mdo</a> ty <3'
url: https://bijumon.github.io
baseurl: ""
paginate: 9
excerpt_separator: <!--more--> 
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-commonmark-ghpages

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - poole-for-jekyll.gemspec
  - _attic

markdown: CommonMarkGhPages
sass:
  sass_dir: _sass
  style: :compressed

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page"

# Replace this value and uncomment to enable Google Analytics tracking
#
# ga_analytics: UA-000000-0

# About/contact
author:
  name: bijumon
  url: https://github.com/bijumon/
  email: _not_specified_@mail.com
  twitter: https://twitter.com/bijupunalor
  github:
    repo: https://github.com/bijumon/bijumon.github.io

# Custom vars
version: 3.0.0
github:
  repo: https://github.com/poole/poole
