# Setup
title: "Happiness, Health and Wealth"
tagline: "The truth may be out there, but the lies are inside your head"
description: "personal blog, built with ruby/jekyll"
url: https://bijumon.github.io
baseurl: ""
paginate: 5
excerpt_separator: <!--more--> 
permalink: pretty
timezone: Asia/Kolkata

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - _attic

sass:
  sass_dir: _sass
  style: :compressed

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page"

# Replace this value and uncomment to enable Google Analytics tracking
#
# ga_analytics: UA-000000-0

# About/contact
author:
  name: bijumon
  url: https://github.com/bijumon/
  email: _not_specified_@mail.cc
  twitter: https://twitter.com/bijupunalor
  github:
    repo: https://github.com/bijumon/bijumon.github.io
