# Setup
title: "Notes"
url: https://updates.vfxwatch.com
baseurl: ""
paginate: 9
excerpt_separator: <!--more--> 
permalink: pretty
timezone: Asia/Kolkata
date_format: "%Y %b %d, %H:%M %Z"

# Gems
plugins:
  - jekyll-seo-tag
  - jekyll-commonmark-ghpages
  - jekyll-paginate

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "table"]

jekyll_compose:
  auto_open: true

sass:
  sass_dir: assets/_sass
  style: :compressed

collections:
  drafts:
    output: true

# Front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      layout: "draft"

# Replace this value and uncomment to enable Google Analytics tracking
#
# ga_analytics: UA-000000-0

# About/contact
author:
  name: bijumon
  url: https://github.com/bijumon/
  twitter: https://twitter.com/bijupunalor
  github:
    repo: https://github.com/bijumon/bijumon.github.io