# Setup
title: thud empty hollow !!!!!
tagline: five exclamation marks, the sure sign of an insane mind -- pratchett
url: https://bijumon.github.com
paginate: 9
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - vendor

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: bijumon
  url: https://twitter.com/bijupunalor
  email: _biju_punalor_@_gee_mail_._com_

# Custom vars
version: 1.0
